# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27d28129bd617a1787dd73e0a5a93bba7f3731e97fabd4f22d6b5610c611b24457c1758e584a27476afda1636f7c22b9e31b03cdab93379e6026524a0996f73e

test:
  secret_key_base: 7ec6a6c3e8d044790618087bc5159eeb9302873fe260cabbdb4ecad176197bfc9d1fdc8b3ff6bbed33e7fe1e5950ce2dd9b67104c1d06c23b6092bbfb35f2565

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
